## Data Preprocessing
## Dataset Source: https://www.kaggle.com/datasets/yasserh/customer-segmentation-dataset
Before start of doing analysis we need to clean and preprocessing the dataset first the approch that we take in this step include:
- Load the dataset in excel format
- check describe and info of each columns in the dataset
- check for missing values and drop
- check duplicated values and drop
- justify the drop of negative values in Quantity columns
- Drop 0 values in UnitPrice
- Normalize the text in Description columns
- Convert the datatyps: InvoiceNo, InvoiceDate, CustomerID
- Create a new columns call TotalSpend from quantity and unitprice

In [88]:
#import the library and ignore warning
import numpy as np
import pandas as pd

import warnings
# Ignore all warnings
warnings.filterwarnings('ignore')

In [89]:
#read the xlxe file
customers = pd.read_excel("../data/raw/Online_Retail.xlsx")
#check header of data
customers.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom

In [90]:
#check info of dataset
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [91]:
#check describes of each columns
customers.describe(include='all')

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909.0,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,25900.0,4070,4223,NaN,NaN,NaN,NaN,38
top,573585.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,1114.0,2313,2369,NaN,NaN,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570,NaN
min,NaN,NaN,NaN,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,2011-03-28 11:34:00,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,2011-07-19 17:17:00,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,2011-10-19 11:27:00,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN

## Missing Values

In [92]:
#check the missing values of each columns
customers.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [93]:
#drop the missing values from CustomerID columns as we can not justify whom purchase that invoice
customers.dropna(subset=['CustomerID'], inplace=True)

In [94]:
#check missing values again 
customers.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

## Duplicated

In [95]:
duplicates = customers[customers.duplicated(keep=False)]
print(duplicates)

       InvoiceNo StockCode                       Description  Quantity  \
485       536409     22111      SCOTTIE DOG HOT WATER BOTTLE         1
489       536409     22866     HAND WARMER SCOTTY DOG DESIGN         1
494       536409     21866       UNION JACK FLAG LUGGAGE TAG         1
517       536409     21866       UNION JACK FLAG LUGGAGE TAG         1
521       536409     22900   SET 2 TEA TOWELS I LOVE LONDON          1
...          ...       ...                               ...       ...
541675    581538     22068       BLACK PIRATE TREASURE CHEST         1
541689    581538     23318    BOX OF 6 MINI VINTAGE CRACKERS         1
541692    581538     22992            REVOLVER WOODEN RULER          1
541699    581538     22694                      WICKER STAR          1
541701    581538     23343      JUMBO BAG VINTAGE CHRISTMAS          1

               InvoiceDate  UnitPrice  CustomerID         Country
485    2010-12-01 11:45:00       4.95     17908.0  United Kingdom
489    2010-12-01 11:45:00       2.10     17908.0  United Kingdom
494    2010-12-01 11:45:00       1.25     17908.0  United Kingdom
517    2010-12-01 11:45:00       1.25     17908.0  United Kingdom
521    2010-12-01 11:45:00       2.95     17908.0  United Kingdom
...                    ...        ...         ...             ...
541675 2011-12-09 11:34:00       0.39     14446.0  United Kingdom
541689 2011-12-09 11:34:00       2.49     14446.0  United Kingdom
541692 2011-12-09 11:34:00       1.95     14446.0  United Kingdom
541699 2011-12-09 11:34:00       2.10     14446.0  United Kingdom
541701 2011-12-09 11:34:00       2.08     14446.0  United Kingdom

[10062 rows x 8 columns]

In [96]:
#verify the duplicate record
customers[(customers['InvoiceNo'] == 581538) & (customers['StockCode'] == 23343)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541666,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom

In [97]:
customers[customers['InvoiceNo'] == 581538]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541628,581538,23193,BUFFALO BILL TREASURE BOOK BOX,6,2011-12-09 11:34:00,2.25,14446.0,United Kingdom
541629,581538,23194,GYMKHANA TREASURE BOOK BOX,1,2011-12-09 11:34:00,2.25,14446.0,United Kingdom
541630,581538,23084,RABBIT NIGHT LIGHT,2,2011-12-09 11:34:00,2.08,14446.0,United Kingdom
541631,581538,22068,BLACK PIRATE TREASURE CHEST,1,2011-12-09 11:34:00,0.39,14446.0,United Kingdom
541632,581538,22956,36 FOIL HEART CAKE CASES,1,2011-12-09 11:34:00,0.79,14446.0,United Kingdom
...,...,...,...,...,...,...,...,...
541697,581538,21194,PINK HONEYCOMB PAPER FAN,1,2011-12-09 11:34:00,0.65,14446.0,United Kingdom
541698,581538,35004B,SET OF 3 BLACK FLYING DUCKS,1,2011-12-09 11:34:00,5.45,14446.0,United Kingdom
541699,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom
541700,581538,21355,TOAST ITS - I LOVE YOU,1,2011-12-09 11:34:00,1.25,14446.0,United Kingdom
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom

In [98]:
#count total of duplicated 
#in defualt it exclude the first duplicate
customers.duplicated().sum()

np.int64(5225)

In [99]:
# Count duplicated rows (excluding the first occurrence)
customers.duplicated(keep=False).sum()

np.int64(10062)

In [100]:
#each row represent each transaction which mean that it shouldn't have any duplicated so we drop the duplicates
customers = customers.drop_duplicates()
customers.shape

(401604, 8)

## Justify of drop duplicated
after inspect again and again about the pattern of duplicated, I decided to drop due to it exactly identical for duplicate. 
I also think about incase if the cashier or whatever scan that product two time which lead to two seperate records but in that case by adjust the quantity number to 2. isn't it much convine?

## Quantity Column

In [101]:
#check the pattern of Quantity <= 0
customers[customers['Quantity'] <= 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [102]:
#to decided remove or keep the row that contain - in quantity
customers[customers['InvoiceNo'] == 'C536391']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom

In [103]:
customers[customers['CustomerID'] == 14527.0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
8963,537159,22112,CHOCOLATE HOT WATER BOTTLE,6,2010-12-05 13:17:00,4.95,14527.0,United Kingdom
8964,537159,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-05 13:17:00,4.95,14527.0,United Kingdom
8965,537159,21479,WHITE SKULL HOT WATER BOTTLE,1,2010-12-05 13:17:00,3.75,14527.0,United Kingdom
8966,537159,22114,HOT WATER BOTTLE TEA AND SYMPATHY,6,2010-12-05 13:17:00,3.95,14527.0,United Kingdom
...,...,...,...,...,...,...,...,...
533807,581114,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2011-12-07 12:19:00,4.95,14527.0,United Kingdom
533808,581114,22835,HOT WATER BOTTLE I AM SO POORLY,2,2011-12-07 12:19:00,4.95,14527.0,United Kingdom
533809,581114,22114,HOT WATER BOTTLE TEA AND SYMPATHY,6,2011-12-07 12:19:00,4.25,14527.0,United Kingdom
533810,581114,21479,WHITE SKULL HOT WATER BOTTLE,2,2011-12-07 12:19:00,4.25,14527.0,United Kingdom
533811,581114,22112,CHOCOLATE HOT WATER BOTTLE,3,2011-12-07 12:19:00,4.95,14527.0,United Kingdom

In [104]:
customers[customers['InvoiceNo'] == 'C581569']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [105]:
#drop the row that contain negative values in quantity columns
customers = customers[customers['Quantity'] > 0]
customers.shape

(392732, 8)

## Justify of drop Quantity <= 0
indicated to this check on the quantity number whether it human input error or it mean returned/canceled i have check on customersID and InvoiceNo which mean that if some part of the invoice got negative and positive values we can though of in put error but due to all the record in that one transaction are negative so it can be return in that case we will drop the row that contain negative quantity

In [106]:
#final description after clean the columns that needed
customers.describe(include='all').round(2)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,392732.0,392732,392732,392732.00,392732,392732.00,392732.00,392732
unique,18536.0,3665,3877,NaN,NaN,NaN,NaN,37
top,576339.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,542.0,2023,2016,NaN,NaN,NaN,NaN,349227
mean,NaN,NaN,NaN,13.15,2011-07-10 19:15:24.576301568,3.13,15287.73,NaN
min,NaN,NaN,NaN,1.00,2010-12-01 08:26:00,0.00,12346.00,NaN
25%,NaN,NaN,NaN,2.00,2011-04-07 11:12:00,1.25,13955.00,NaN
50%,NaN,NaN,NaN,6.00,2011-07-31 12:02:00,1.95,15150.00,NaN
75%,NaN,NaN,NaN,12.00,2011-10-20 12:53:00,3.75,16791.00,NaN
max,NaN,NaN,NaN,80995.00,2011-12-09 12:50:00,8142.75,18287.00,NaN
std,NaN,NaN,NaN,181.59,NaN,22.24,1713.57,NaN

StockCode and Description Columns should have equal number of Unique

## StockCode and Description Columns

In [107]:
#check stockcode record
customers['StockCode'].unique()

array(['85123A', 71053, '84406B', ..., '90214Z', 90089, 23843],
      shape=(3665,), dtype=object)

In [108]:
#check number of Description
customers['Description'].unique()

array(['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN',
       'CREAM CUPID HEARTS COAT HANGER', ...,
       'PINK CRYSTAL SKULL PHONE CHARM',
       'CREAM HANGING HEART T-LIGHT HOLDER',
       'PAPER CRAFT , LITTLE BIRDIE'], shape=(3877,), dtype=object)

In [109]:
#randomly check stockcode number
#show inconsistent writing
customers[customers['StockCode'] == '90014C']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
142063,548545,90014C,SILVER/BLACK ORBIT NECKLACE,1,2011-03-31 19:12:00,9.95,13118.0,United Kingdom
305558,563698,90014C,SILVER/BLACK ORBIT NECKLACE,2,2011-08-18 13:46:00,9.95,14667.0,United Kingdom
504721,578993,90014C,SILVER AND BLACK ORBIT NECKLACE,1,2011-11-27 15:38:00,2.95,15987.0,United Kingdom

In [110]:
#show inconsistent writing
customers[customers['StockCode'] == 21112].sample(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
33905,539307,21112,"SWISS ROLL TOWEL, PINK SPOTS",120,2010-12-16 17:43:00,1.25,13694.0,United Kingdom
43770,540126,21112,"SWISS ROLL TOWEL, PINK SPOTS",96,2011-01-05 10:45:00,1.25,13798.0,United Kingdom
389657,570488,21112,SWISS ROLL TOWEL PINK SPOTS,2,2011-10-10 17:12:00,5.79,14096.0,United Kingdom
135214,547886,21112,SWISS ROLL TOWEL PINK SPOTS,6,2011-03-28 09:21:00,2.95,13652.0,United Kingdom
321691,565197,21112,SWISS ROLL TOWEL PINK SPOTS,6,2011-09-01 16:16:00,2.95,13376.0,United Kingdom
48851,540477,21112,"SWISS ROLL TOWEL, PINK SPOTS",24,2011-01-07 14:49:00,1.25,13233.0,United Kingdom
130863,547514,21112,SWISS ROLL TOWEL PINK SPOTS,6,2011-03-23 14:00:00,2.95,17486.0,United Kingdom
41229,539761,21112,"SWISS ROLL TOWEL, PINK SPOTS",24,2010-12-22 10:29:00,1.25,17593.0,United Kingdom
9661,537209,21112,"SWISS ROLL TOWEL, PINK SPOTS",1,2010-12-05 15:12:00,2.95,14606.0,United Kingdom
96924,544597,21112,SWISS ROLL TOWEL PINK SPOTS,1,2011-02-21 17:42:00,2.95,16014.0,United Kingdom

Indicate that Description was writing inconsistency which is same meaning difference writing so we will clean it to the same text

In [111]:
# clean text
customers['Description'] = customers['Description'].str.lower().str.strip()

# fix inconsistent descriptions
#keep only the most writing style in ach same meaning
desc_map = (
    customers.groupby(['StockCode', 'Description'])
    .size()
    .reset_index(name='count')
    .sort_values(['StockCode','count'], ascending=[True,False])
    .drop_duplicates('StockCode')
)

desc_map

desc_dict = dict(zip(desc_map['StockCode'], desc_map['Description']))

#replace the description in dataframe into consistency
customers['Description'] = customers['StockCode'].map(desc_dict)

In [112]:
print("Unique StockCodes:", customers['StockCode'].nunique())
print("Unique Descriptions:", customers['Description'].nunique())
print("Missing Descriptions:", customers['Description'].isna().sum())

Unique StockCodes: 3665
Unique Descriptions: 3639
Missing Descriptions: 0

still not equal, which mean that one description get more than one stockcode

In [113]:
#show description that got more than 1 stock code
customers.groupby('Description')['StockCode'].nunique().loc[lambda x: x > 1]

Description
bathroom metal sign                2
colouring pencils brown tube       2
columbian candle rectangle         2
columbian candle round             3
eau de nile jewelled photoframe    2
french floral cushion cover        2
french lattice cushion cover       2
french paisley cushion cover       2
frosted white base                 2
heart t-light holder               2
metal sign,cupcake single hook     3
paper lantern 9 point snow star    2
pink fairy cake cushion cover      2
pink flock glass candleholder      2
pink flowers rabbit easter         2
pink jewelled photo frame          2
retro plastic 70's tray            2
retro plastic daisy tray           2
retro plastic polka tray           2
rose du sud cushion cover          2
round blue clock with sucker       2
set of 4 fairy cake placemats      2
square cherry blossom cabinet      2
white bamboo ribs lampshade        2
Name: StockCode, dtype: int64

In [114]:
#same description differences stockcode because it got difference prices as well
customers[customers['Description'] == 'frosted white base']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
29965,538836,79403,frosted white base,1,2010-12-14 13:09:00,0.85,12748.0,United Kingdom
86884,543610,79403,frosted white base,12,2011-02-10 14:30:00,0.85,16425.0,United Kingdom
91904,544160,79406,frosted white base,6,2011-02-16 12:49:00,0.22,16494.0,United Kingdom
103399,545062,79403,frosted white base,2,2011-02-27 14:07:00,0.85,12748.0,United Kingdom
105989,545302,79403,frosted white base,10,2011-03-01 12:46:00,0.85,14506.0,United Kingdom
123844,546917,79403,frosted white base,12,2011-03-18 09:17:00,0.85,14911.0,EIRE
151829,549569,79403,frosted white base,3,2011-04-10 15:15:00,0.85,15547.0,United Kingdom
167717,551003,79406,frosted white base,24,2011-04-26 09:44:00,0.22,16456.0,United Kingdom
237735,557884,79403,frosted white base,12,2011-06-23 13:35:00,0.85,17759.0,United Kingdom
240443,558101,79406,frosted white base,72,2011-06-26 13:56:00,0.22,18112.0,United Kingdom
266698,560264,79403,frosted white base,12,2011-07-17 13:46:00,0.85,12833.0,United Kingdom
283337,561710,79406,frosted white base,5,2011-07-29 11:45:00,0.22,13827.0,United Kingdom
294103,562688,79403,frosted white base,12,2011-08-08 13:53:00,0.85,13869.0,United Kingdom
305252,563661,79406,frosted white base,9,2011-08-18 11:23:00,0.22,13048.0,United Kingdom
397806,571205,79403,frosted white base,12,2011-10-14 12:41:00,0.85,15620.0,United Kingdom
436451,574149,79406,frosted white base,24,2011-11-03 11:29:00,0.22,13709.0,United Kingdom
520200,580272,79403,frosted white base,1,2011-12-02 12:52:00,0.85,15547.0,United Kingdom

In [115]:
#show description that got one tock code
customers.groupby('Description')['InvoiceNo'].nunique().loc[lambda x: x >= 1].head()

Description
10 colour spaceboy pen          242
12 coloured party balloons      139
12 daisy pegs in wood box        62
12 egg house painted wood        64
12 hanging eggs hand painted      7
Name: InvoiceNo, dtype: int64

In [116]:
customers[customers['Description'] == '12 daisy pegs in wood box']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
565,536412,21448,12 daisy pegs in wood box,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
578,536412,21448,12 daisy pegs in wood box,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
28486,538638,21448,12 daisy pegs in wood box,1,2010-12-13 14:16:00,1.65,17231.0,United Kingdom
31895,539019,21448,12 daisy pegs in wood box,4,2010-12-15 14:12:00,1.65,17551.0,United Kingdom
32846,539185,21448,12 daisy pegs in wood box,2,2010-12-16 11:53:00,1.65,16470.0,United Kingdom
...,...,...,...,...,...,...,...,...
356855,568060,21448,12 daisy pegs in wood box,2,2011-09-23 13:11:00,1.65,14546.0,United Kingdom
364370,568657,21448,12 daisy pegs in wood box,1,2011-09-28 12:22:00,1.65,16460.0,United Kingdom
378845,569669,21448,12 daisy pegs in wood box,2,2011-10-05 13:47:00,1.65,14730.0,United Kingdom
382011,569897,21448,12 daisy pegs in wood box,1,2011-10-06 16:01:00,1.65,17813.0,United Kingdom
398999,571268,21448,12 daisy pegs in wood box,2,2011-10-16 12:06:00,1.65,15351.0,United Kingdom

Base on our inspect we realize that difference stockcode into the same description it mean the price difference could be because of the size and number of quantity as well

## InvoiceNo, CustomerID and InvoiceDate Type

In [117]:
#convert datatypes
customers['InvoiceNo'] = customers['InvoiceNo'].astype(int)
customers['CustomerID'] = customers['CustomerID'].astype(int)
customers['InvoiceDate'] = pd.to_datetime(customers['InvoiceDate'])

#check datatype of the columns
customers.dtypes

InvoiceNo               int64
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int64
Country                object
dtype: object

In [118]:
#check format of InvoiceDate
customers['InvoiceDate'].unique()

<DatetimeArray>
['2010-12-01 08:26:00', '2010-12-01 08:28:00', '2010-12-01 08:34:00',
 '2010-12-01 08:35:00', '2010-12-01 08:45:00', '2010-12-01 09:00:00',
 '2010-12-01 09:01:00', '2010-12-01 09:02:00', '2010-12-01 09:09:00',
 '2010-12-01 09:32:00',
 ...
 '2011-12-09 12:09:00', '2011-12-09 12:16:00', '2011-12-09 12:19:00',
 '2011-12-09 12:20:00', '2011-12-09 12:21:00', '2011-12-09 12:23:00',
 '2011-12-09 12:25:00', '2011-12-09 12:31:00', '2011-12-09 12:49:00',
 '2011-12-09 12:50:00']
Length: 17286, dtype: datetime64[ns]

## UnitPrice Column

In [119]:
#inspect the row that unit price equal to 0
customers[customers['UnitPrice'] == 0.0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
9302,537197,22841,round cake tin vintage green,1,2010-12-05 14:02:00,0.0,12647,Germany
33576,539263,22580,advent calendar gingham sack,4,2010-12-16 14:36:00,0.0,16560,United Kingdom
40089,539722,22423,regency cakestand 3 tier,10,2010-12-21 13:45:00,0.0,14911,EIRE
47068,540372,22090,paper bunting retrospot,24,2011-01-06 16:41:00,0.0,13081,United Kingdom
47070,540372,22553,plasters in tin skulls,24,2011-01-06 16:41:00,0.0,13081,United Kingdom

In [120]:
customers[customers['UnitPrice'] == 0].groupby('InvoiceNo').size().reset_index(name='zero_price_count').head()

   InvoiceNo  zero_price_count
0     537197                 1
1     539263                 1
2     539722                 1
3     540372                 2
4     541109                 1

In [121]:
#inspect one invoice with unitprice = 0
customers[(customers['InvoiceNo'] == 574920) & (customers['UnitPrice'] == 0.0)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
446793,574920,22899,children's apron dolly girl,1,2011-11-07 16:34:00,0.0,13985,United Kingdom
446794,574920,23480,mini lights woodland mushrooms,1,2011-11-07 16:34:00,0.0,13985,United Kingdom

In [122]:
#inspect one invoice with unitprice = 0
customers[(customers['InvoiceNo'] == 574920)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
446773,574920,85099B,jumbo bag red retrospot,10,2011-11-07 16:34:00,2.08,13985,United Kingdom
446774,574920,22663,jumbo bag dolly girl design,10,2011-11-07 16:34:00,2.08,13985,United Kingdom
446775,574920,22385,jumbo bag spaceboy design,10,2011-11-07 16:34:00,2.08,13985,United Kingdom
446776,574920,22386,jumbo bag pink polkadot,10,2011-11-07 16:34:00,2.08,13985,United Kingdom
446777,574920,22457,natural slate heart chalkboard,6,2011-11-07 16:34:00,2.95,13985,United Kingdom
446778,574920,22083,paper chain kit retrospot,6,2011-11-07 16:34:00,2.95,13985,United Kingdom
446779,574920,22910,paper chain kit vintage christmas,12,2011-11-07 16:34:00,2.95,13985,United Kingdom
446780,574920,23313,vintage christmas bunting,10,2011-11-07 16:34:00,4.95,13985,United Kingdom
446781,574920,23480,mini lights woodland mushrooms,4,2011-11-07 16:34:00,3.75,13985,United Kingdom
446782,574920,20727,lunch bag black skull.,10,2011-11-07 16:34:00,1.65,13985,United Kingdom
446783,574920,20725,lunch bag red retrospot,10,2011-11-07 16:34:00,1.65,13985,United Kingdom
446784,574920,22384,lunch bag pink polkadot,10,2011-11-07 16:34:00,1.65,13985,United Kingdom
446785,574920,20728,lunch bag cars blue,10,2011-11-07 16:34:00,1.65,13985,United Kingdom
446786,574920,22379,recycling bag retrospot,5,2011-11-07 16:34:00,2.10,13985,United Kingdom
446787,574920,22381,toy tidy pink polkadot,5,2011-11-07 16:34:00,2.10,13985,United Kingdom
446788,574920,23569,tradtional alphabet stamp set,8,2011-11-07 16:34:00,4.95,13985,United Kingdom
446789,574920,23084,rabbit night light,12,2011-11-07 16:34:00,2.08,13985,United Kingdom
446790,574920,23328,set 6 school milk bottles in crate,4,2011-11-07 16:34:00,3.75,13985,United Kingdom
446791,574920,23255,childrens cutlery circus parade,4,2011-11-07 16:34:00,4.15,13985,United Kingdom
446792,574920,23256,childrens cutlery spaceboy,4,2011-11-07 16:34:00,4.15,13985,United Kingdom
446793,574920,22899,children's apron dolly girl,1,2011-11-07 16:34:00,0.00,13985,United Kingdom
446794,574920,23480,mini lights woodland mushrooms,1,2011-11-07 16:34:00,0.00,13985,United Kingdom

In [123]:
#remove the rows that contain 0 values
customers = customers[customers['UnitPrice'] > 0]
customers.shape

(392692, 8)

As we check that invoice transection we realize that it shouldn't because of human error, but it could be the promotion or free gift instead so we will drop the row that contain UnitPrice = 0 as well to not confuse and make it wrong for calculate Monterey

In [124]:
#we don't detect any outlier or remove as we belives that the real transaction might contain the high volume of purchase as well

## Create TotalSpend Column

In [135]:
#create a new column call TotalSpend
customers['TotalSpend'] = (customers['Quantity'] * customers['UnitPrice'])

In [136]:
#final check dataframe
customers.sample(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSpend
264865,560125,22589,cardholder gingham star,1,2011-07-15 10:44:00,2.55,18118,United Kingdom,2.55
520255,580276,21890,s/6 wooden skittles in cotton bag,2,2011-12-02 12:59:00,3.25,16426,United Kingdom,6.50
165858,550830,23207,lunch bag alphabet design,10,2011-04-21 10:29:00,1.65,13534,United Kingdom,16.50
2147,536562,22423,regency cakestand 3 tier,2,2010-12-01 15:08:00,12.75,13468,United Kingdom,25.50
331013,565934,22865,hand warmer owl design,12,2011-09-08 10:45:00,2.10,18222,United Kingdom,25.20
242546,558355,82578,kitchen metal sign,4,2011-06-28 14:58:00,0.55,13614,United Kingdom,2.20
241053,558124,22385,jumbo bag spaceboy design,10,2011-06-27 10:17:00,2.08,12493,France,20.80
478543,577092,22617,baking set spaceboy design,3,2011-11-17 16:35:00,4.95,15136,United Kingdom,14.85
55277,540984,22882,number tile vintage font 3,1,2011-01-12 15:44:00,1.95,14167,United Kingdom,1.95
289129,562220,84380,set of 3 butterfly cookie cutters,12,2011-08-03 14:19:00,1.25,15150,United Kingdom,15.00

In [137]:
customers.describe(include='all')

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSpend
count,392692.000000,392692,392692,392692.000000,392692,392692.000000,392692.000000,392692,392692.000000
unique,NaN,3665,3639,NaN,NaN,NaN,NaN,37,NaN
top,NaN,85123A,white hanging heart t-light holder,NaN,NaN,NaN,NaN,United Kingdom,NaN
freq,NaN,2023,2023,NaN,NaN,NaN,NaN,349203,NaN
mean,560590.875047,NaN,NaN,13.119702,2011-07-10 19:13:07.771892480,3.125914,15287.843865,NaN,22.631500
min,536365.000000,NaN,NaN,1.000000,2010-12-01 08:26:00,0.001000,12346.000000,NaN,0.001000
25%,549234.000000,NaN,NaN,2.000000,2011-04-07 11:12:00,1.250000,13955.000000,NaN,4.950000
50%,561874.000000,NaN,NaN,6.000000,2011-07-31 12:02:00,1.950000,15150.000000,NaN,12.450000
75%,572061.000000,NaN,NaN,12.000000,2011-10-20 12:53:00,3.750000,16791.000000,NaN,19.800000
max,581587.000000,NaN,NaN,80995.000000,2011-12-09 12:50:00,8142.750000,18287.000000,NaN,168469.600000
std,13087.063759,NaN,NaN,180.492832,NaN,22.241836,1713.539549,NaN,311.099224

In [138]:
customers[customers['UnitPrice'] <= 0.01]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSpend
157195,550193,PADS,pads to match all cushions,1,2011-04-15 09:27:00,0.001,13952,United Kingdom,0.001
279045,561226,PADS,pads to match all cushions,1,2011-07-26 10:13:00,0.001,15618,United Kingdom,0.001
359871,568200,PADS,pads to match all cushions,1,2011-09-25 14:58:00,0.001,16198,United Kingdom,0.001
361741,568375,BANK CHARGES,bank charges,1,2011-09-26 17:01:00,0.001,13405,United Kingdom,0.001

In [140]:
#load data into clean csv file
# save cleaned dataset
customers.to_csv("../data/processed/online_retail_clean.csv", index=False)